# Form implementation generated from reading ui file 'access_files.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from access import xternal
from internal_view import i_app

class Ui_access(object):
    def setupUi(self, access):
        access.setObjectName("access")
        access.resize(554, 333)
        self.internal = QtWidgets.QPushButton(access)
        self.internal.setGeometry(QtCore.QRect(60, 80, 191, 171))
        self.internal.setObjectName("internal")
        self.external = QtWidgets.QPushButton(access)
        self.external.setGeometry(QtCore.QRect(300, 80, 191, 171))
        self.external.setObjectName("external")

        self.retranslateUi(access)
        QtCore.QMetaObject.connectSlotsByName(access)

    def retranslateUi(self, access):
        _translate = QtCore.QCoreApplication.translate
        access.setWindowTitle(_translate("access", "Dialog"))
        self.internal.setText(_translate("access", "Internal View"))
        self.external.setText(_translate("access", "External View"))

        self.external.clicked.connect(self.open_x)
        self.internal.clicked.connect(self.open_i)

    def open_x(self):
        xternal()

    def open_i(self):
        self.app = i_app()
        self.app.show()
        QtWidgets.QDialog.close(self)

class accss(QtWidgets.QDialog, Ui_access):
    def __init__(self, *args, obj=None, **kwargs):
        super(accss, self).__init__(*args, **kwargs)
        self.setupUi(self)