# Form implementation generated from reading ui file 'auth_meth.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from usrpass_login import usr_pwd
from ssh_login import login
from pin_login import pin

class Ui_auth(object):
    def setupUi(self, auth):
        auth.setObjectName("auth")
        auth.resize(280, 358)
        self.UnP = QtWidgets.QPushButton(auth)
        self.UnP.setGeometry(QtCore.QRect(80, 110, 121, 41))
        self.UnP.setObjectName("UnP")
        self.pin = QtWidgets.QPushButton(auth)
        self.pin.setGeometry(QtCore.QRect(100, 180, 81, 41))
        self.pin.setObjectName("pin")
        self.ssh = QtWidgets.QPushButton(auth)
        self.ssh.setGeometry(QtCore.QRect(100, 250, 81, 41))
        self.ssh.setObjectName("ssh")
        self.label = QtWidgets.QLabel(auth)
        self.label.setGeometry(QtCore.QRect(30, 40, 221, 41))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")

        self.retranslateUi(auth)
        QtCore.QMetaObject.connectSlotsByName(auth)

    def retranslateUi(self, auth):
        _translate = QtCore.QCoreApplication.translate
        auth.setWindowTitle(_translate("auth", "Dialog"))
        self.UnP.setText(_translate("auth", "Username"))
        self.UnP.clicked.connect(self.usr_lg)

        self.pin.setText(_translate("auth", "PIN"))
        self.pin.clicked.connect(self.pine)

        self.ssh.setText(_translate("auth", "SSH KEYS"))
        self.ssh.clicked.connect(self.ssh_l)

        self.label.setText(_translate("auth", "Choose Authentication Method"))

    def usr_lg(self):
        self.usr = usr_pwd()
        self.usr.show()
        QtWidgets.QDialog.close(self)

    def pine(self):
        self.pin = pin()
        self.pin.show()
        QtWidgets.QDialog.close(self)

    def ssh_l(self):
        self.log = login()
        self.log.show()
        QtWidgets.QDialog.close(self)

class Auth(QtWidgets.QDialog , Ui_auth):
    def __init__(self, *args, obj=None, **kwargs):
        super(Auth, self).__init__(*args, **kwargs)
        self.setupUi(self)
 