# Form implementation generated from reading ui file 'create_usr.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from generate import userInfo
from view_dets import view

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(333, 335)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 101, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 80, 221, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 101, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 190, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 260, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter your name"))
        self.label_2.setText(_translate("Dialog", "Create 4-digit pin"))
        self.pushButton.setText(_translate("Dialog", "Create"))
        self.pushButton.clicked.connect(self.create_usr)
    
    def create_usr(self):
        name = self.lineEdit.text()
        pin = self.lineEdit_2.text()
        usr = userInfo(self, name, pin, QtWidgets)
        self.ve = view()
        self.ve.nm.setText(usr['user'])
        self.ve.passw.setText(usr['pwd'])
        self.ve.pin.setText(usr['pin'])
        self.ve.pub.setText(usr['publickey'])
        self.ve.pri.setText(usr['privatekey'])
        self.ve.exec()

class NewUsr(QtWidgets.QDialog , Ui_Dialog):
    def __init__(self, *args, obj=None, **kwargs):
        super(NewUsr, self).__init__(*args, **kwargs)
        self.setupUi(self)
