# Form implementation generated from reading ui file 'pin_login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from access import validate_pin
from access_files import accss

class Ui_pin(object):
    def setupUi(self, pin):
        pin.setObjectName("pin")
        pin.resize(240, 297)
        self.usr = QtWidgets.QLineEdit(pin)
        self.usr.setGeometry(QtCore.QRect(60, 42, 113, 31))
        self.usr.setObjectName("usr")
        self.usr_label = QtWidgets.QLabel(pin)
        self.usr_label.setGeometry(QtCore.QRect(60, 10, 61, 51))
        self.usr_label.setObjectName("usr_label")
        self.lineEdit = QtWidgets.QLineEdit(pin)
        self.lineEdit.setGeometry(QtCore.QRect(60, 100, 113, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(pin)
        self.label.setGeometry(QtCore.QRect(60, 70, 61, 21))
        self.label.setObjectName("label")
        self.login = QtWidgets.QPushButton(pin)
        self.login.setGeometry(QtCore.QRect(80, 180, 81, 31))
        self.login.setObjectName("login")

        self.retranslateUi(pin)
        QtCore.QMetaObject.connectSlotsByName(pin)

    def retranslateUi(self, pin):
        _translate = QtCore.QCoreApplication.translate
        pin.setWindowTitle(_translate("pin", "Dialog"))
        self.usr_label.setText(_translate("pin", "Username"))
        self.label.setText(_translate("pin", "Enter PIN"))
        self.login.setText(_translate("pin", "View"))

        self.login.clicked.connect(self.validate_p)

    def validate_p(self):
        p_usr = self.usr.text()
        pin = self.lineEdit.text()
        validate_pin(self, p_usr, pin, accss, QtWidgets)

class pin(QtWidgets.QDialog , Ui_pin):
    def __init__(self, *args, obj=None, **kwargs):
        super(pin, self).__init__(*args, **kwargs)
        self.setupUi(self)
