# Form implementation generated from reading ui file 'ssh_login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from access import validate_ssh
from access_files import accss

class Ui_login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 523)
        self.usr = QtWidgets.QLineEdit(Dialog)
        self.usr.setGeometry(QtCore.QRect(110, 42, 191, 31))
        self.usr.setObjectName("usr")
        self.usr_label = QtWidgets.QLabel(Dialog)
        self.usr_label.setGeometry(QtCore.QRect(110, 10, 101, 51))
        self.usr_label.setObjectName("usr_label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(110, 100, 401, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 80, 101, 31))
        self.label.setObjectName("label")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 240, 401, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 101, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 320, 131, 51))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.usr_label.setText(_translate("Dialog", "Username"))
        self.label.setText(_translate("Dialog", "Public Key"))
        self.label_2.setText(_translate("Dialog", "Private Key"))
        self.pushButton.setText(_translate("Dialog", "View"))

        self.pushButton.clicked.connect(self.validate_s)

    def validate_s(self):
        p_usr = self.usr.text()
        pub = self.textEdit.toPlainText()
        pri = self.textEdit_2.toPlainText()
        validate_ssh(self, p_usr, pub, pri, accss, QtWidgets)

class login(QtWidgets.QDialog , Ui_login):
    def __init__(self, *args, obj=None, **kwargs):
        super(login, self).__init__(*args, **kwargs)
        self.setupUi(self)
