# Form implementation generated from reading ui file 'usrpass_login.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from access import validate_usr
from access_files import accss

class Ui_usr_pwd(object):
    def setupUi(self, usr_pwd):
        usr_pwd.setObjectName("usr_pwd")
        usr_pwd.resize(352, 308)
        self.login = QtWidgets.QPushButton(usr_pwd)
        self.login.setGeometry(QtCore.QRect(100, 220, 141, 41))
        self.login.setObjectName("login")
        self.usr = QtWidgets.QLineEdit(usr_pwd)
        self.usr.setGeometry(QtCore.QRect(80, 50, 191, 31))
        self.usr.setObjectName("usr")
        self.label = QtWidgets.QLabel(usr_pwd)
        self.label.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(usr_pwd)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 61, 21))
        self.label_2.setObjectName("label_2")
        self.pwd = QtWidgets.QLineEdit(usr_pwd)
        self.pwd.setGeometry(QtCore.QRect(80, 140, 191, 31))
        self.pwd.setObjectName("pwd")

        self.retranslateUi(usr_pwd)
        QtCore.QMetaObject.connectSlotsByName(usr_pwd)

    def retranslateUi(self, usr_pwd):
        _translate = QtCore.QCoreApplication.translate
        usr_pwd.setWindowTitle(_translate("usr_pwd", "Dialog"))
        self.login.setText(_translate("usr_pwd", "View"))
        self.label.setText(_translate("usr_pwd", "Username"))
        self.label_2.setText(_translate("usr_pwd", "Password"))

        self.login.clicked.connect(self.validate_u)

    def validate_u(self):
        p_usr = self.usr.text()
        p_pass = self.pwd.text()
        validate_usr(self, p_usr, p_pass, accss, QtWidgets)

class usr_pwd(QtWidgets.QDialog , Ui_usr_pwd):
    def __init__(self, *args, obj=None, **kwargs):
        super(usr_pwd, self).__init__(*args, **kwargs)
        self.setupUi(self)
