# Form implementation generated from reading ui file 'view_dets.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyperclip as pc

class Ui_details_popup(object):
    def setupUi(self, details_popup):
        details_popup.setObjectName("details_popup")
        details_popup.resize(290, 332)
        self.nm = QtWidgets.QLineEdit(details_popup)
        self.nm.setEnabled(False)
        self.nm.setGeometry(QtCore.QRect(40, 20, 121, 20))
        self.nm.setObjectName("nm")
        self.passw = QtWidgets.QLineEdit(details_popup)
        self.passw.setEnabled(False)
        self.passw.setGeometry(QtCore.QRect(40, 60, 121, 20))
        self.passw.setObjectName("pass")
        self.pin = QtWidgets.QLineEdit(details_popup)
        self.pin.setEnabled(False)
        self.pin.setGeometry(QtCore.QRect(40, 100, 121, 20))
        self.pin.setObjectName("pin")
        self.pub = QtWidgets.QTextEdit(details_popup)
        self.pub.setEnabled(False)
        self.pub.setGeometry(QtCore.QRect(40, 130, 121, 71))
        self.pub.setObjectName("pub")
        self.pri = QtWidgets.QTextEdit(details_popup)
        self.pri.setEnabled(False)
        self.pri.setGeometry(QtCore.QRect(40, 220, 121, 71))
        self.pri.setObjectName("pri")
        self.copy = QtWidgets.QPushButton(details_popup)
        self.copy.setGeometry(QtCore.QRect(160, 20, 75, 23))
        self.copy.setObjectName("copy")
        self.copy_2 = QtWidgets.QPushButton(details_popup)
        self.copy_2.setGeometry(QtCore.QRect(160, 60, 75, 23))
        self.copy_2.setObjectName("copy_2")
        self.copy_3 = QtWidgets.QPushButton(details_popup)
        self.copy_3.setGeometry(QtCore.QRect(160, 100, 75, 23))
        self.copy_3.setObjectName("copy_3")
        self.copy_4 = QtWidgets.QPushButton(details_popup)
        self.copy_4.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.copy_4.setObjectName("copy_4")
        self.copy_5 = QtWidgets.QPushButton(details_popup)
        self.copy_5.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.copy_5.setObjectName("copy_5")

        self.retranslateUi(details_popup)
        QtCore.QMetaObject.connectSlotsByName(details_popup)

    def retranslateUi(self, details_popup):
        _translate = QtCore.QCoreApplication.translate
        details_popup.setWindowTitle(_translate("details_popup", "Form"))
        self.copy.setText(_translate("details_popup", "Copy"))
        self.copy_2.setText(_translate("details_popup", "Copy"))
        self.copy_3.setText(_translate("details_popup", "Copy"))
        self.copy_4.setText(_translate("details_popup", "Copy"))
        self.copy_5.setText(_translate("details_popup", "Copy"))

        self.copy.clicked.connect(self.copy1)
        self.copy_2.clicked.connect(self.copy2)
        self.copy_3.clicked.connect(self.copy3)
        self.copy_4.clicked.connect(self.copy4)
        self.copy_5.clicked.connect(self.copy5)

    def copy1(self):
        pc.copy(self.nm.text())

    def copy2(self):
        pc.copy(self.passw.text())

    def copy3(self):
        pc.copy(self.pin.text())

    def copy4(self):
        pc.copy(self.pub.toPlainText())

    def copy5(self):
        pc.copy(self.pri.toPlainText())

class view(QtWidgets.QDialog, Ui_details_popup):
    def __init__(self, *args, obj=None, **kwargs):
        super(view, self).__init__(*args, **kwargs)
        self.setupUi(self)
